### ISSUE TITLE
Is the web page being hosted?

### ISSUE THREAD

**Issue by sunrabbit123** [Ubinquitous/FTF_FindTheFollowers#1]
I was impressed with your project.
And I wanted to use it simply, but I don't think the web is being hosted.

If you are burdened with hosting, I recommend the following methods.

1. github pages
    this solution has `gh-pages` package and use case is very simple 
    insert script at package.json
    ```json
    "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "deploy": "gh-pages -d build"
      },
    ```
   
    and add workflow
    ```yml
    name: github pages
    
    on:
      push:
        branches:
          - main
    
    jobs:
      deploy:
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v2
    
          - name: Setup Node
            uses: actions/setup-node@v2.1.2
            with:
              node-version: "14.x"
    
          - run: yarn
          - run: yarn build
    
          - name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.ACCESS_TOKEN }}
              publish_dir: ./build
    ```

    The solution will work beautifully.
2. railway
3. vercel
4. aws cloud front

The following four services are available free of charge or at reasonable prices.

thank you for reading it.
